"""initial_migration

Revision ID: 0c992b80befb
Revises: 
Create Date: 2026-09-12 17:12:31.654448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c992b80befb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###